import type { Event } from '../types/events.types'

export const data: Event[] = [
  {
    sale_amount: 'S/. 0.00',
    is_contract: false,
    is_liquidation: false,
    is_amount_pending_deposit: '3554.00',
    id: 1721,
    contract_id: 149,
    parent_id: 0,
    type_product_id: 3,
    home_group_id: 0,
    code: null,
    title_small: '9° Aniversario de Castillo Grande con Corazón Serrano',
    title_large: '¡No te lo pierdas!',
    meta_description: null,
    slug: '9-aniversario-de-castillo-grande-con-corazon-serrano',
    price_normal: 40,
    price_online: 40,
    price_partner: 40,
    stock: 10134,
    description:
      '<h2 style="text-align: center;"><strong>🎉 &iexcl;La fiesta m&aacute;s esperada del a&ntilde;o est&aacute; por llegar! 🎉</strong></h2>\r\n<p>&nbsp;</p>\r\n<p><strong>Castillo Grande</strong> celebra su <strong>9&deg; Aniversario</strong> con un evento &uacute;nico que no te puedes perder. Y para hacerlo a&uacute;n m&aacute;s especial, tendremos como <strong>artista invitado a Coraz&oacute;n Serrano</strong>, la ic&oacute;nica banda que nos har&aacute; bailar con sus mejores &eacute;xitos de cumbia y m&uacute;sica tropical.&nbsp;</p>\r\n<p>&iexcl;Acomp&aacute;&ntilde;anos en una noche llena de ritmo y emociones! Prep&aacute;rate para disfrutar de un show inolvidable con la m&uacute;sica que nos une y nos hace gozar.&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>&iexcl;Te esperamos para cantar, bailar y festejar juntos!</p>\r\n<p>&nbsp;</p>',
    conditions: null,
    event_info:
      '<p>Para ingresar al evento debes mostrar impreso o en el celular el c&oacute;digo QR adjunto en el presente correo.</p>\r\n<p><br />Es tu responsabilidad mantener la confidencialidad del c&oacute;digo de acceso y el c&oacute;digo QR.</p>',
    poster: '1383-GRILLA-CORAZON-SERRANO.jpg',
    poster_mobile: null,
    cupon_expire_in: 30,
    sales_deadline: null,
    to_deliver: false,
    delivery_cost: '0.00',
    to_coupon: false,
    active: true,
    featured: true,
    promotion: false,
    deleted_at: null,
    created_at: null,
    updated_at: '2025-09-02T21:08:27.000000Z',
    shop_id: 39,
    video_url: null,
    video_id: '',
    partner_commission: '5.00',
    vaope_commission: '1.00',
    vaope_commission_type: 1,
    sale_comission: '2.00',
    is_stock: true,
    fecha_evento: '24/10/2025',
    hora_evento: '20:00:00',
    link_grupo_cerrado: null,
    address: 'Complejo Deportivo Aliaga, CASTILLO GRANDE - HUÁNUCO',
    location_id: 638,
    croquis: '118-fondo.png',
    status: 1,
    can_be_sold: true,
    correlative_count: 245,
    group_tickets: 1,
    add_ticket_image: null,
    is_comision_scaled: 0,
    ticketing_fotter_text:
      'La responsabilidad de este boleto es exclusiva del usuario. No compartir ni publicar. Se recomienda llevar impreso.',
    ticketing_fotter_img: null,
    ticketing_super_img: '2301-TICKED-CORAZON-SERRANO.jpg',
    payment_flow: 'interactive',
    is_landing_page: false,
    max_by_client: 10,
    show_in_home: 1,
    is_nameable: false,
    product_liquidation_operations_count: 0,
    product_documents_count: 1,
    master_events: {
      id: '1',
      position: 2,
      name: 'Publicado',
      description: 'Evento publicado',
      color: 'success',
      active: true,
      next_status: null,
    },
    notes_count: 2,
    children_allowed: 0,
    children_age: 18,
    map_svg: 0,
    notes_class: 'warning',
    code_ico: 'fa-exclamation-circle',
    is_by_zone: 0,
    notes: [
      {
        id: '172',
        user: 'Claudia Rodriguez',
        code_status: 'info',
        code_status_name: 'Informacion',
        description: '- Se generan 04 entradas vip por solicitud del organizador',
      },
      {
        id: '174',
        user: 'Samuel Chuquista',
        code_status: 'warning',
        code_status_name: 'Advertencia',
        description: 'Esto es un advertencia',
      },
    ],
    productTerms: [
      {
        id: 13019,
        name: 'ENTRADAS',
      },
      {
        id: 13403,
        name: 'ASIENTOS',
      },
      {
        id: 13405,
        name: 'BOX',
      },
    ],
    userProducts: [],
    shop: {
      id: 39,
      shop_category_id: 1,
      type_doc: 'RUC',
      ruc: '20608361074',
      slug: 'jp-producciones-generales-eirl',
      name: 'JP Producciones Generales EIRL',
      business_name: 'JP Producciones Generales EIRL',
      commission: 10,
      logo: null,
      banner: null,
      description: null,
      district_id: '150140',
      address: 'Jr. El Escorial 306 of. 403',
      condition: null,
      dnifile_path: null,
      status: null,
      phone: '941327406',
      email: 'patrick@jpproduccionesperu.com',
      email_secondary: null,
      website: null,
      is_delivery: true,
      is_show_in_ticket: 1,
      is_to_collect: 0,
      latitude: null,
      longitude: null,
      shapes: [],
      delivery_cost: 0,
      visa_merchant_id: 'true',
      visa_user: 'true',
      visa_pwd: 'true',
      active: true,
      deleted_at: null,
      created_at: '2022-06-21T15:47:11.000000Z',
      updated_at: '2023-08-29T11:06:05.000000Z',
      opening_hour_from: null,
      opening_hour_to: null,
      opening_days: null,
      banco: 'BCP',
      tipo_cuenta: 'AHORRO_SOLES',
      numero_cuenta: '1949924003053',
      cci: '00219400992400305398',
      nombre_representante_legal: 'Jean Patrick Remond Alayza',
      dni_representante_legal: '72866346',
      facebook_pixel: null,
      executive_id: 1,
      created_by: 1,
      updated_by: 1,
      priority: 4,
      executive: {
        id: 1,
        name: 'Samuel Chuquista',
        document_type: 'DNI',
        document_number: '12345678',
        email: 'samuel@vaope.com',
        email_verified_at: null,
        two_factor_confirmed_at: null,
        api_token: null,
        avatar: '1.jpg',
        active: 1,
        created_at: '2021-05-14T02:22:34.000000Z',
        updated_at: '2026-01-21T01:41:45.000000Z',
        deleted_at: null,
        is_seller: true,
        is_validador: true,
        is_download_data: true,
        product_id: 0,
        lastlogin: '2026-01-21T01:41:45.000000Z',
        app_validation_type: 1,
        last_app_sync: '2024-12-02T20:15:33.000000Z',
        phone: '984399924',
        is_view_validation_report: 1,
        is_temporal: 0,
        date_expirate_temporal_user: null,
        local_id: 0,
        photo_url:
          'https://www.gravatar.com/avatar/67b78b19a5469cc59767ea4389479434.jpg?s=200&d=https%3A%2F%2Fui-avatars.com%2Fapi%2FSamuel+Chuquista',
      },
    },
    contract: {
      id: 149,
      shop_id: 39,
      number: '202309-00149',
      file: '202309-00149-20240129131135.pdf',
      reference: 'Contrato Firmado',
      date_from: '2023-09-23',
      date_to: '2024-12-31',
      created_at: '2023-09-23T09:51:39.000000Z',
      updated_at: '2024-01-29T13:11:36.000000Z',
      deleted_at: null,
      estado: 1,
      file_firmado: '5258-202309-00149.pdf',
      cpd_porcentaje: '3.75',
      cpd_fijo: '0.60',
      cpd_minimo: '1.00',
      cv_porcentaje: '3.00',
      cv_fijo: '0.00',
      cv_minimo: '1.00',
      cv_adicional_cliente: '0.00',
      cv_cortesia: '0.50',
      cv_punto_venta: '0.50',
      send_on: null,
    },
  },
]
